### ISSUE TITLE
some expression found bug

### ISSUE THREAD

**Issue by btfak** [Knetic/govaluate#128]
```
        r, err := govaluate.NewEvaluableExpression("x%10==8")
	if err != nil {
		log.Fatal(err)
		return
	}

	parameters := make(map[string]interface{})
	parameters["x"] = int64(71111112902814738)

	result, err := r.Evaluate(parameters)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("result is %v", result)
```

result should be true, but i got false

NEED HELP ~

**Comment by CxdInitial** [comment]
`govaluate` treat all numeric value as `float64`. `float64`'s max safe integer value is 9007199254740991. Obviously, 71111112902814738 is much larger, so it get rounded and become unsafe to compute and compare.

To fix this bug, some check can be added to issue an error before real evaluation, or just add integer type to this library.

**Comment by invzhi** [comment]
We met this bug too. Any plan to fix it?
