### ISSUE TITLE
project should probably be archived if abandoned

### ISSUE THREAD

**Issue by alexec** [Knetic/govaluate#148]
No updates since 2017 and no issues replied to. The project appears to be abandoned?

**Comment by Knetic** [comment]
It's not abandoned, it has quite a few thousand users/companies pulling and using it every day. While I would love to devote more time, circumstances have limited the time for language design that I have. 

It is a constant goal of mine to come back and finish a less-limited version of accessors (the `.` operator, which calls members of struct params), among a host of other things that downstream users would find valuable. I don't consider this version to be the final version, but can't give an estimate on when further work will make it out of local branches and into the public repo (i've given estimates in other issues, but ended up eating crow on them).

**Comment by alexec** [comment]
> It's not abandoned

Yay! My issue was a sneaky way of finding out ;) 

I really glad to hear that. We've got many (1000s) user using code that relies on Goevaluate, and I feel a lot more confident now.
