### ISSUE TITLE
unable to compare string to any operator symbol (as string)

### ISSUE THREAD

**Issue by mirdhyn** [Knetic/govaluate#22]
For example, following code fail with `runtime error: index out of range` :
```go
expression, err := govaluate.NewEvaluableExpression("'foo' == '-'")
result, err := expression.Evaluate(nil)
```

Same thing with any of the operator symbols (-, +, /, * and %)

**Comment by Knetic** [comment]
Looks like I missed some TokenKind checks when the expression gets parsed out into stages. f0224e3439bece781a1dd44618a5483a9212ec4b should fix any of these panic cases where strings are misinterpreted.

Sorry for the bug!

**Comment by mirdhyn** [comment]
Your commit successfully fixed the issue.
Thank you very much, that was a very fast reaction!
