### ISSUE TITLE
NaN / +Inf detection in govaluate?

### ISSUE THREAD

**Issue by toni-moreno** [Knetic/govaluate#42]
Hi @Knetic .

I'm working with this wonderful toot to allow on the fly evaluation from a network gatherer tool.

https://github.com/toni-moreno/snmpcollector/blob/master/pkg/snmpmetric.go#L286

When evaluating an expression like that  C=A/B , I got 

NaN when A=0 and B=0
+Inf when B = 0.

but the in the below expression, the err = nil.

```go
result, err := s.expr.Evaluate(parameters)
if err != nil {
	log.Errorf("Error in metric %s On EVAL string: %s : ERROR : %s", ID, evalString, err)
	return
}
```

There is any easy way to check if NaN or Inf are returned? ( is result a string)  What other valid results could I get  with err == nil ?

**Comment by Knetic** [comment]
The easiest way to check if a float64 is infinity / NaN is in the standard library `math` package; [Inf](https://golang.org/pkg/math/#Inf) and [IsNaN](https://golang.org/pkg/math/#IsNaN). If you know you're getting a numeric value back, you can use those to check that it's what you're expecting. I'd recommend that for now :]

The NaN / infinity behavior is all part of the usual floating-point handling standard that Go itself implements, this library doesn't do anything special with NaN or infinity. Generally, this library defers to Go in just about every case - all operators (well, except for `IN`) either go to standard library functions or native Go arithmetic operators. So it ought to act about as closely as possible to Go itself as far as errors and return values are concerned.

But now that I'm thinking about it, I'm struggling to find a reason why unsignalled NaN/infinity would be useful in an expression; it feels like the proper behavior should be that this library gives you an error when it can't resolve an expression to a single, unambiguous result. Go ahead and use the functions in `math` for now, I'll look and see if treating NaN/infinity as error conditions would break anyone.

**Comment by toni-moreno** [comment]
Hi @Knetic I've already  done, as you suggest me.

https://github.com/toni-moreno/snmpcollector/commit/585814409b0cc10b405bdec40874f457c589d770

I'm also thinking about it, and IMHO this behavior should be optional.  Perhaps for some scenarios the NaN and Inf is not really an error. 

Indeed Is an error for me only because my database backend doesn't support it  yet. ( https://github.com/influxdata/influxdb/issues/4089) In the future perhaps could be a valid value.

Thank You very much
