### ISSUE TITLE
How to Get parameters from expression?

### ISSUE THREAD

**Issue by toni-moreno** [Knetic/govaluate#43]
There is any way to get parameters contained on an arbitrary expression?.

Supose this:
```golang
govaluate.NewEvaluableExpression("(requests_made * requests_succeeded / 100) >= 90");
```

I need a way to get an parameter array with "request_made","request_succeded" 

I need it to query a database for values to replace them.

Thanks you very much!!

**Comment by bkrn** [comment]
I believe you're looking for EvaluableExpression.Vars()

```
/*
	Returns an array representing the variables contained in this EvaluableExpression.
*/
func (this EvaluableExpression) Vars() []string {
	var varlist []string
	for _, val := range this.Tokens() {
		if val.Kind == VARIABLE {
			varlist = append(varlist, val.Value.(string))
		}
	}
	return varlist
}
```

**Comment by Knetic** [comment]
bkrn is correct - `Vars` is the right approach. Closing, but feel free to reopen if there are any problems.
