### ISSUE TITLE
Wrong result for boolean expression

### ISSUE THREAD

**Issue by lxn** [Knetic/govaluate#44]
`false && true || true` evaluates to `false`, while `true || false && true` evaluates to `true`.

Edit: Of course both should evaluate to true.

**Comment by Knetic** [comment]
Fixed as of https://github.com/Knetic/govaluate/commit/66c7476fa887bd1ce65a8b11427aba3661cea0bc.

Looks like I wrote a bad test, which led me to write bad code. Added the two test cases from your post, fixed the bug, and everything looks good now. Sorry for the bug!

**Comment by lxn** [comment]
No worries, thanks for the quick fix and your nice library :-)
