### ISSUE TITLE
Another boolean expression problem

### ISSUE THREAD

**Issue by lxn** [Knetic/govaluate#45]
Hi!

Just hit another problematic case:

`true && true || false && false` should return `true`, but returns `false`, while `true && true || false` as well as `true && true || (false && false)` both return `true`, as expected.

**Comment by Knetic** [comment]
Man, these are going to be the death of me haha. Fixed as of https://github.com/Knetic/govaluate/commit/5598166b6fc09f038e53f628eec79f0c004a4299.

I'd been erroneously trying to keep `&&` and `||` at equal precedence for a long time. [This table](http://en.cppreference.com/w/c/language/operator_precedence) (which i even link to in the readme) clearly shows they're not equal precedence. With this change I finally broke them out into separate precedents and now everything works as expected.

Knock on wood, but this should be the last of these precedence bugs.

**Comment by lxn** [comment]
Thanks for the fix :-)
