### ISSUE TITLE
Test if expression will yield a numeric or boolean

### ISSUE THREAD

**Issue by davidsonff** [Knetic/govaluate#48]
Would it be possible to add a function which would tell you whether or not a given expression yielded a boolean or numeric value without submitting any parameter values?

**Comment by Knetic** [comment]
Unfortunately no, not without knowing the parameters. Some operators produce different types based on the inputs. For instance: `foo + bar` could concatenate a string if both parameters are strings, or it could add numbers together if they are both numbers. One returns a string, the other a number, but unless you know what the values of `foo` and `bar`, you can't know what will come out the other end.

I don't know what your use case is, but you can probably do a type switch after evaluating the expression. Like:

```
var result interface{}

expression := govaluate.NewEvaluableExpression("foo + bar")
result, _ = expression.Evaluate(yourParameters)

switch result.(type) {
    case float64: 
        doNumericStuff(result.(float64))
    case bool:
        doBoolStuff(result.(bool))
}
```

**Comment by davidsonff** [comment]
I'm building an app which uses govaluate as a trigger evaluator. In the UI, I need to check that an expression typed in to the app by a user will result in a boolean (trigger is true or not). I check that it's a valid expression, but I can't check if it will yield a boolean.

**Comment by bkrn** [comment]
What would you expect the expression `[param1] == [param2] ? 'moose' :
true` to cause your requested function to return?

**Comment by davidsonff** [comment]
False as the above could return 'moose' if I am understanding correctly...

**Comment by davidsonff** [comment]
I'm wondering if I can test by passing in just numeric values and testing if the result is boolean. For now, only numeric parameters will be permitted. I'm not sure of the mathmatical (or logical) validity of that approach, but it's a thought...

Also, I was just thinking: isn't string concatenation and comparison a completely different operation from numerical addition and equivalency? Shouldn't those really be separate operators? Shouldn't all string operations really be separate from numerical ones?

**Comment by Knetic** [comment]
Passing numeric values as parameters and "smoketesting" the expression is probably your best bet. I don't know the design constraints of your app, but maybe you could treat any non-bool values as `false`, and let the user know somehow that they wrote something that didn't give expected output? A couple users of this library do monitor alerting with it, and treat non-bool results as "no-op" results.

It might be _possible_ to get a list of types that an expression can return, but that would rely on a lot of very implementation-specific details that aren't in the public api for the library, and wouldn't be able to tell you much in a lot of cases (like the one @bkrn mentioned).

As for operator overloading, this library mostly follows Go/python/ruby conventions. `+` in those languages acts like a `strcat`, `>` acts like a lexicographic compare, etc. The alternative to that is defining brand-new operators for those sorts of operations (which breaks from what users are used to), or to provide them as a sort of "standard library" of functions (making it so you can call `strcat` or `strcmp`  functions without passing them in) - which leads to a whole mess of questions about the scope and interface of such a standard library.

**Comment by davidsonff** [comment]
I think I'll pass in a "1" for every parameter and see if it yields a bool type. I think that should catch the vast majority of cases. I don't know if that has to be the case logically, but I would think if there are any where it doesn't, they'd be mostly outliers...

**Comment by Knetic** [comment]
Closing since it seems like there's something close enough to a solution.
