### ISSUE TITLE
Support BigDecimal

### ISSUE THREAD

**Issue by TamalSaha** [Knetic/govaluate#51]
Hi,
Can BigDecimal be supported in this library? https://github.com/shopspring/decimal is a golang implementation of BigDecimal. Support for BigDecimal will allow for using this library for financial calculation.

Thanks.

**Comment by Knetic** [comment]
I can see the advantage of supporting bigdecimal, but unfortunately there's not a clean way to integrate it into the library. Doing so would involve either moving all numeric calculation from `float64` to their bigdecimal equivalent, or costing even more in type checking for just about every operator.

I've been toying with some concepts that may allow users to select what kind of numeric representation they want in an expression, but it's a far-future kind of thing. The trade-offs just aren't worth it right now, sorry!
