### ISSUE TITLE
`Invalid token: '+['` error in expression `"a"+[parameter]`

### ISSUE THREAD

**Issue by llonchj** [Knetic/govaluate#59]
`Invalid token: '+['` error in expression `"a"+[parameter]`

...And expression `"a" + [parameter]` is valid

**Comment by Knetic** [comment]
Good catch, fixed as of https://github.com/Knetic/govaluate/commit/ed428fc1d628f009bd7fbf100ff72feba3527753.

**Comment by llonchj** [comment]
Thanks @Knetic
