### ISSUE TITLE
many IN array feature 

### ISSUE THREAD

**Issue by shaikemarc** [Knetic/govaluate#66]
Hi,

First, thanks for the library, its awesome!
I have a question on how to use/extent the library to fit my needs. I intend to use it in order to eval questionnaires, while every questionnaire composed of dif questions types. Some are simple, for instance a dates compare, single answer IN array etc.., but how can i implement MANY in ARRAY, e.g. my use selects many choices and there are many possible answers?
I checked the library and this expression "(2) IN (1, 2, 3)" works as oppose to "(1,2) IN (1, 2, 3)". 
I thought about extend it myself but as my expression will be used for many questionnaires i want to cache the right side (1,2,3) into a map to achieve performance... 
How can it be done?

thanks!

**Comment by Knetic** [comment]
Hey there, thanks for using the library!

It sounds like you're after something that compares two arrays, and returns `true` if there are any elements present in both arrays. If this is the case, I'd recommend that you write an [`ExpressionFunction`](https://github.com/Knetic/govaluate#functions) that performs this check for you. It could look something like;

```
functions := map[string]govaluate.ExpressionFunction {
    "innerExists": func(args ...interface{}) (interface{}, error) {
        source := args[0].([]interface{})
        other := args[1].([]interface{})

        for _, value := range source {
            for _, otherValue := range other {
                if value == otherValue {
                    return true, nil
                }
            }
        }

        return false, nil
    },
}
```

And your expression could do something like;

```
innerExists((1, 2), (1, 2, 3))
```

**Comment by shaikemarc** [comment]
Thanks for the quick response. Extending the library using custom fn was my initial thought.
In my case the left side (AKA: source) is a parameter being populated by the user and the right side (AKA: other) is evaluated just once, while the expression is built. 
How can i cache it into for instance a map and boost performance? Do i have a context per expression?

**Comment by Knetic** [comment]
You shouldn't have to worry too much about performance - the library has some optimizations to make things like allocating arrays of literals (e.g., `(1, 2, 3)`) very fast. Even if both of your arrays are parameters, it won't cost much more than if one or both were made of literals.

Personally I'd just give it a try, and if you run into performance bottlenecks, we can look into optimizing things. But you shouldn't have any trouble if one or both sides are parameters.

**Comment by guyannanfei25** [comment]
``` go
    goExp := "arrayIn(rules, rules2)"
    funcs := map[string]govaluate.ExpressionFunction {
        "arrayIn" : func(args ...interface{}) (interface{}, error) {
            fmt.Printf("args0 [%#v] type[%T], args[1] [%#v] type[%T]\n", args[0], args[0], args[1], args[1])
            fmt.Printf("args[%#v] type[%T] len[%#v]\n", args, args, len(args))
            src := args[0].([]interface{})
            dst := args[1].([]interface{})

            for _, v1 := range src {
                for _, v2 := range dst {
                    if v1 == v2 {
                        return true, nil
                    }
                }
            }

            return false, nil
        },
    }
    expr, err := govaluate.NewEvaluableExpressionWithFunctions(goExp, funcs)
    if err != nil {
        panic(err)
    }

    fmt.Printf("vars [%#v]\n", expr.Vars())
    pars := map[string]interface{} {
        "rules" : []interface{}{"111", "222", "333"},
        "rules2" : []interface{}{"11", "222"},
    }
   ret, err := expr.Evaluate(pars)
````

output:
>vars [[]string{"rules", "rules2"}]
>args0 ["111"] type[string], args[1] ["222"] type[string]
>args[[]interface {}{"111", "222", "333", []interface {}{"11", "222"}}] type[[]interface {}] len[4]
>panic: interface conversion: interface {} is string, not []interface {}

it doesnot take rules([]interface{}{"111", "222", "333"}) as args[0],
is there something I use wrong?
