### ISSUE TITLE
Cannot pass arrays to functions

### ISSUE THREAD

**Issue by maja42** [Knetic/govaluate#91]
I implemented a "len" expression function, which should return the number of elements in an array or, if a string is passed, the string length.

It receives one argument (=the array or string).

The expression looks like this:

```
"len( \"text\" )"
"len( (1,2,3,4) )"
```

Both of these calls should return the number 4, as there are 4 characters in the string / 4 elements in the array. 

The first expression works flawlessly. However, govaluate does not seem to correctly parse the array literal syntax. Instead, it treats the values as four different arguments to the function.

The same happens, if I register an array variable:

```
arr := []interface{}{1,2,3,4}
e, _ := govaluate.NewEvaluableExpressionWithFunctions("len( arr )", ...)
e.Evaluate(map[string]interface{}{ "arr": arr })
```
This code substitutes the variable "arr" with the underlying go-array, and - again - calls my custom "len"-operator with 4 arguments.

This means, that I have a problem as soon as the array contains strings:

`"len( (\"text\") )"`

This array contains one element, which is a string. I expect the number "1" to be returned. However, govaluate passes me a string, and I return "4" instead.

The only way to work around this issue is to implement separate functions for strings and arrays. But I'd like to avoid that and actually *know* the difference between a passed array and multiple arguments within expression functions.

**Comment by Knetic** [comment]
This is another symptom of the bug raised in #89, it's not intentional. Going to close this one as a duplicate,  the fix for that will also fix the behavior shown here.
