### ISSUE TITLE
String escaping: Cannot transition token types from STRING [] to VARIABLE

### ISSUE THREAD

**Issue by maja42** [Knetic/govaluate#94]
When evaluating the following expression: `"\"abcd\""`, the result is the string `"abcd"` - which is correct. (Yes, the string starts and ends with double-quotes)

Now, govaluate also supports single-ticks for string constants. So I would like to use them, and avoid the quote-escaping.
However, when I evaluate this expression: `'"abcd"'`, I get an error:

> Cannot transition token types from STRING [] to VARIABLE [abcd]

I expect goevaluate to return  `"abcd"`.

After further investigation, when evaluating  `'\"abcd\"'`, the result is in fact  `"abcd"`. However, in this case I would actually expect the result to be  `\"abcd\"` (the result should contain the backslashes).

It seems to me that govaluate does not differentiate between double-quoted and single-quoted strings, and always expects double-quotes to be escaped. Which doesn't really make sense.

**Comment by maja42** [comment]
And the error-message isn't really helpful.

**Comment by Knetic** [comment]
You're correct, double and single quotes are, for the moment, treated identically in this library's parser. The historical reason for this is that initially only single-quotes were supported (similar to SQL), double quotes were added later.

I may end up looking at changing the semantics of this, but for the immediate term, that's just how it is.
