### ISSUE TITLE
Reason to not use struct pointer receivers

### ISSUE THREAD

**Issue by mr-karan** [Knetic/govaluate#98]
Firstly, thanks for the amazing library, great work 👍.

I was browsing through the source code and noticed that you are [not](https://github.com/Knetic/govaluate/blob/master/EvaluableExpression.go#L131) using struct pointer receivers. I am just curious to know is there any specific reason behind this? 

Thanks!

**Comment by Knetic** [comment]
Thanks for using the library!

I never found a need for them to be pointer receivers. By design, evaluation never modifies anything in the structure, so passing by-value makes that more clear. Plus, the objects are not particularly large, so passing around by-value hasn't yet been a huge deal.
