### ISSUE TITLE
Need help with evaluation using structs

### ISSUE THREAD

**Issue by asimpatnaik** [Knetic/govaluate#99]
Hi,
Apologies if this is a duplicate issue / request. I have the below requirement:
Expression - "foo.a + foo.b"
foo is a struct -
type foo struct {
	a int
	b int
}
I'm getting runtime errorn when i do the following:

func method6(){
	obj := &foo{1, 2}
	expression, _ := govaluate.NewEvaluableExpression("foo.a + foo.b")

	parameters := make(map[string]interface{}, 8)
	parameters["foo"] = *obj
	result, err := expression.Evaluate(parameters)
	if err != nil{
		fmt.Println(err)
	} else {
		fmt.Println(result)
	}
}

Kindly help.

Regards,
Asim.

**Comment by hate13** [comment]
hi, you should keep the field be exported.
Like this:
`
type foo struct {
    A int
    B int
}

...

expression, _ := govaluate.NewEvaluableExpression("foo.A + foo.B")
`

**Comment by asimpatnaik** [comment]
Thanks a lot. It worked.

Regards,
Asim.
